// Simulated accuracy on the NCS venue. Writes docs/benchmark-sim.md and src/data/bench.json (shown in the app panel).
//   npm run bench
import { writeFileSync } from 'node:fs';
import { TOUR_SECONDS, tourPose } from '../src/data/tour';
import { NCS } from '../src/data/venue';
import { standAt, walk, type Score, type TrialOptions } from '../src/engine/evaluate';
import type { EstimatorKind } from '../src/engine/estimators';
import type { FilterKind } from '../src/engine/filters';
import { pointInPolygon, polygonCentroid } from '../src/engine/geometry';
import type { Pose } from '../src/engine/simulator';

const SIGMAS = [2, 4, 6, 8];
const ESTIMATORS: EstimatorKind[] = ['proximity', 'centroid', 'trilateration'];
const FILTERS: FilterKind[] = ['kalman', 'ema', 'none'];
const SEEDS = [1, 2, 3];
const DWELL_S = 5;

// Room-centre spots: every space whose centroid falls inside it.
const SPOTS: Pose[] = NCS.floors.flatMap((f) =>
  f.spaces
    .map((s) => ({ s, c: polygonCentroid(s.polygon) }))
    .filter(({ s, c }) => pointInPolygon(c, s.polygon))
    .map(({ c }) => ({ floor: f.level, x: c[0], y: c[1] })),
);

// Average over seeds (medians/p90s averaged, which is fine for a table at this precision).
function avg(run: (o: TrialOptions) => Score, base: Omit<TrialOptions, 'seed'>): Score {
  const rs = SEEDS.map((seed) => run({ ...base, seed }));
  const mean = (k: keyof Score) => rs.reduce((s, r) => s + r[k], 0) / rs.length;
  return { fixes: mean('fixes'), median: mean('median'), p90: mean('p90'), floorRate: mean('floorRate'), spaceRate: mean('spaceRate') };
}

export interface BenchRow {
  scenario: 'walk' | 'rooms';
  estimator: EstimatorKind;
  filter: FilterKind;
  sigma: number;
  median: number;
  p90: number;
  floorRate: number;
  spaceRate: number;
}

const rows: BenchRow[] = [];
for (const filter of FILTERS)
  for (const estimator of ESTIMATORS)
    for (const sigma of SIGMAS) {
      // Filter comparison only at the default noise level, to keep the table short.
      if (filter !== 'kalman' && sigma !== 4) continue;
      const base = { estimator, filter, sigma };
      const w = avg((o) => walk(NCS, tourPose, TOUR_SECONDS, o), base);
      const r = avg((o) => standAt(NCS, SPOTS, DWELL_S, o), base);
      rows.push({ scenario: 'walk', ...base, median: w.median, p90: w.p90, floorRate: w.floorRate, spaceRate: w.spaceRate });
      rows.push({ scenario: 'rooms', ...base, median: r.median, p90: r.p90, floorRate: r.floorRate, spaceRate: r.spaceRate });
    }

const m = (v: number) => v.toFixed(1);
const pct = (v: number) => `${(v * 100).toFixed(1)}%`;
const table = (scenario: BenchRow['scenario'], pick: (r: BenchRow) => boolean) =>
  [
    '| Estimator | Filter | Noise σ (dB) | Median error (m) | 90th pct (m) | Floor correct | Space correct |',
    '|---|---|---|---|---|---|---|',
    ...rows
      .filter((r) => r.scenario === scenario && pick(r))
      .map((r) => `| ${r.estimator} | ${r.filter} | ${r.sigma} | ${m(r.median)} | ${m(r.p90)} | ${pct(r.floorRate)} | ${pct(r.spaceRate)} |`),
  ].join('\n');

const md = `# Simulated accuracy (NCS)

**Simulated, not measured.** Generated by \`npm run bench\` (scripts/bench.ts) on ${new Date().toISOString().slice(0, 10)}.
Re-run it whenever the venue, the tour, the radio model or the engine changes.

Setup: ${NCS.beacons.length} beacons on the traced NCS floors (src/data/ncs.json), radio model from docs/SPEC.md
(log-distance n = 2.2, RSSI@1m = −59 dBm, Gaussian noise σ, 10% packet drop, 18 dB per floor slab, 3 dB through an atrium void).
One scan every 250 ms. Each number is the mean over seeds ${SEEDS.join(', ')}.
Horizontal error is counted only on fixes that picked the right floor; the floor column covers the rest.

The simulator has no walls, furniture, people or multipath, so real-world error will be larger.
Treat these as a comparison between methods, not as a promise of field accuracy.

## Walk (${Math.round(TOUR_SECONDS)} s tour: entrance → atrium → floor 2 galleries → floor 3 galleries → back, 1.2 m/s)

${table('walk', (r) => r.filter === 'kalman')}

## Standing in rooms (${SPOTS.length} room centres, fresh locator, last fix after ${DWELL_S} s)

${table('rooms', (r) => r.filter === 'kalman')}

## Filters (σ = 4 dB)

Walk:

${table('walk', (r) => r.sigma === 4)}

Rooms:

${table('rooms', (r) => r.sigma === 4)}
`;

writeFileSync(new URL('../docs/benchmark-sim.md', import.meta.url), md);
const round = (v: number, d: number) => Math.round(v * 10 ** d) / 10 ** d;
writeFileSync(
  new URL('../src/data/bench.json', import.meta.url),
  JSON.stringify(
    rows.map((r) => ({ ...r, median: round(r.median, 2), p90: round(r.p90, 2), floorRate: round(r.floorRate, 4), spaceRate: round(r.spaceRate, 4) })),
    null,
    1,
  ) + '\n',
);
console.log(md);
