import type { Library } from './schema';
import raw from './melville.json';

/** Melville Library, generated by scripts/trace-melville.mjs (never hand-edit melville.json). */
export const MELVILLE = raw as unknown as Library; // JSON infers never[] for empty arrays
